# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
#
default: &default
  adapter: mysql2
  pool: 5
  encoding: utf8
  username: eugeneidan
  password: smarterTree
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: genkeyFoodOrder_development

test:
  <<: *default
  database: genkeyFoodOrder_test

production:
  <<: *default
  database: genkeyFoodOrder_production
  username: genkeyFoodOrder
  password: <%= ENV['GENKEYFOODORDER_DATABASE_PASSWORD'] %>
